#!/bin/bash

file=$1

printpoly()
{
  printf '    { "type": "Feature", "properties": { "name": "%s" }, "geometry": { "type": "Polygon", "coordinates": [ [ ' "$poly"
  for ((i=0; i<("${#points[@]}"); i++))
  do
    printf '[%s],' "${points["$i"]}";
  done;
  printf '[%s]' "${points["0"]}";
  printf '] ] } },\n';
}

printf '{ "type": "FeatureCollection", "features": [\n'
sed -e 1d -e 's/\r//' -e 's/,144.*//' "$file" |
while read -r line;
do
  if ! [[ $line =~ ^144.*$ ]];
  then
    if [[ -n $poly ]];
    then
      printpoly
    fi;
    poly=$line;
    points=();
  else
    points+=($line)
  fi;
done

printf '  ] }\n'
