#!/usr/bin/env bash

s="2019 Autumn Confest Map (Export2009)003.geojson";
s2=${s/geojson/ndjson};
cat "$s" |
sed 's/, *"\(EntityHandle\|Linetype\|SubClasses\)": *"[^"]*"//g' |
sed 's/\(XAttribute\|Lnkg\) *{[^}]*}//g' |
sed 's/, *"[^"]*": *\(null\|""\)//g' |
geojson2ndjson > "$s2";
grep '"Layer": *"[^"]*"' -o "$s2" | sort -u |
  while read -r l;
  do
    lfile=${l%\"};
    lfile=${lfile##*\"}
    grep -F "$l" "$s2" | ndjson2geojson > layers/"$lfile".geojson;
  done
rm "$s2"
